import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import "./responsive.css";
import HeaderWrapper from "@/component/Header/HeaderWrapper";
import FooterWrapper from "@/component/Footer/FooterWrapper";


export const metadata: Metadata = {
    title: "The CometBid Technology Foundation ",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="">
                <HeaderWrapper />
                {children}
                <FooterWrapper />
            </body>
        </html>
    );
}
